// Auto-generated from icons/svgs/. Do not edit by hand.
export type IconName =
  "alert-triangle" | "arrow-right" | "arrow-up" | "award" | "banknote" | "bar-chart-2" | "briefcase" | "building-2" | "calendar" | "check" | "check-circle" | "clock" | "code" | "credit-card" | "database" | "file-text" | "filter" | "globe" | "heart" | "layers" | "link" | "lock" | "mail" | "message-circle" | "package" | "phone" | "pie-chart" | "refresh-cw" | "rocket" | "search" | "settings" | "shield" | "star" | "tag" | "target" | "thumbs-up" | "trending-up" | "user" | "users" | "x-circle" | "zap";

export const ICON_NAMES = [
  "alert-triangle",
  "arrow-right",
  "arrow-up",
  "award",
  "banknote",
  "bar-chart-2",
  "briefcase",
  "building-2",
  "calendar",
  "check",
  "check-circle",
  "clock",
  "code",
  "credit-card",
  "database",
  "file-text",
  "filter",
  "globe",
  "heart",
  "layers",
  "link",
  "lock",
  "mail",
  "message-circle",
  "package",
  "phone",
  "pie-chart",
  "refresh-cw",
  "rocket",
  "search",
  "settings",
  "shield",
  "star",
  "tag",
  "target",
  "thumbs-up",
  "trending-up",
  "user",
  "users",
  "x-circle",
  "zap",
] as const;
